### ISSUE TITLE
Is it safe to have jspecify be an optional dependency?

### ISSUE THREAD

**Issue by bowbahdoe** [jspecify/jspecify#389] opened 2023-06-02 03:15 UTC
Apologies, I am bumping up against my knowledge of bytecode compatibility.

If I compile a class or module with nullness annotations, can consumers use that class/module without having jspecify on the class or module path?

**Comment by cpovirk** [comment] 2023-06-02 14:54
Thanks, we should write something about this, and I'll keep this issue open until we do.

In principle, it should be safe to omit the annotations jar around at runtime. That said, there have been bugs in this area, [like this one fixed in JDK 9](https://bugs.openjdk.org/browse/JDK-8152174) (which we at least [documented here](https://github.com/jspecify/jspecify/wiki/version-compatibility#runtime), though I just noticed and fixed a mistake :)).

Note that Maven's `provided`/`optional` also omits the annotations jar at _compile time_, and that can lead to [various issues](https://github.com/google/guava/wiki/UseGuavaInYourBuild#what-about-guavas-own-dependencies) in certain setups. (Other tools, like Gradle and Bazel, have actual ways of setting up "compile-only" dependencies, which would avoid those problems.)

(I'll also add that we're likely to keep to this pace of adding maybe an annotation per year, so we hope that the _jar size_ doesn't become a reason for people to feel the need to omit the dependency. There are, of course, other downsides to having a dependency, though we'd expect those to be minor in most cases, too, especially once _everyone_ is using our jar, anyway :-P)

**Comment by bowbahdoe** [comment] 2023-06-03 17:06
For my case, I want students who download my jar directly to just have it work.

```java
import org.jspecify.annotations.NullMarked;

@NullMarked
module dev.mccue.json {
    requires static org.jspecify;

    exports dev.mccue.json;
    exports dev.mccue.json.stream;
}
```

```xml
        <dependency>
            <groupId>org.jspecify</groupId>
            <artifactId>jspecify</artifactId>
            <version>0.3.0</version>
            <scope>provided</scope>
        </dependency>
```

In which case the "cost" of depending on jspecify is low

**Comment by cpovirk** [comment] 2023-06-05 14:43
Sounds good. I'd guess that that will work fine, but there will be no substitute for actually trying it out :)

**Comment by bowbahdoe** [comment] 2023-06-07 14:55
Would it be reccomended to use 

```java
    requires static org.jspecify;
```

or 

```java
    requires static transitive org.jspecify;
```

Will that make a difference to the reference checker?

**Comment by cpovirk** [comment] 2023-06-07 15:23
Based on my skim of https://github.com/ben-manes/caffeine/issues/535, I would suggest trying `requires static transitive`, though [maybe someday you'd be able to omit `transitive` without triggering warnings](https://mail.openjdk.org/pipermail/jigsaw-dev/2021-July/014682.html). Really, I wouldn't be surprised if the reference checker doesn't care what you do. But my guess would be that, if it _did_ care, it would prefer having `transitive`.

**Comment by bowbahdoe** [comment] 2023-07-06 16:02
@cpovirk So I finally got around to actually testing what would happen here. 

Take these two modules. The only difference between them is that one requires static jspecify, the other requires static transitive.

[json-0.2.4-static.jar.zip](https://github.com/jspecify/jspecify/files/11970068/json-0.2.4-static.jar.zip)
[json-0.2.4-static-transitive.jar.zip](https://github.com/jspecify/jspecify/files/11970070/json-0.2.4-static-transitive.jar.zip)

(zipped because github doesn't like jars)

When I compile a dependent module without jspecify on the module path, the `requires static transitive` version fails.

## `requires static org.jspecify`

![static](https://github.com/jspecify/jspecify/assets/5004262/9afc4f79-c2e2-479e-9bce-af8da09b98e4)

## `requires static transitive org.jspecify`

![static-transitive](https://github.com/jspecify/jspecify/assets/5004262/df058814-3a32-4d62-87f7-af9531133f67)

So it looks like the "correct" way to not have runtime dependence on the jspecify jar is to use `requires static`, but if you compile with `-Xlint:all -Werror` like all good children should then only the `requires static transitive` will work.

This feels like something that should be raised on compiler-dev to see what the best solution is/if this exact category of "type exposed from module is okay iff its just an annotation w/ no enum components" can be accounted for.

**Comment by agentgt** [comment] 2023-08-01 19:03
> Is this not just an eclipse bug? Java seems to behave properly by hiding the annotations from reflective callers when they aren't present.

Let us ignore what Java aka Open JDK javac currently does. Javac does lots of incorrect things for TYPE_USE at the moment.

TYPE_USE annotations are part of the type. Think of it has hiding `Optional`.

> That doesn't really work when you want someone to not have to use maven infrastructure to use the jar.

I agree. I'm saying ideally it requires transitive because the JSpecify annotations are retention=RUNTIME that means some one could access them reflectively... regardless of modules... you see when you ask a class for a single annotation it it will try to load all of them. This is one of Micronauts arguments for saving memory is using their compile time annotation access tools (this is just a side note).

> Isn't the way optional+provided deps are broken is that they don't let you provide a "compile only" dependency? That doesn't feel like it affects this situation?

It is broken in that different tools will do different things. Graal VM native, running with jpackage, Maven, insert other build tool, Eclipse, etc all have different ideas what *optional* is.

The modular JDK idea of *optional* is really only the service loader. But you are right that if we are talking about what is capable with the current JDK modular: 

> "optional+provided deps are broken is that they don't let you provide a "compile only" dependency" 

is correct.

The reason what I mention is relevant is because we are talking about tools and tools have to do different things than the JDK.

**Comment by bowbahdoe** [comment] 2023-08-01 19:24
> TYPE_USE annotations are part of the type. Think of it has hiding `Optional`.

I'm more thinking of it like hiding the `String` in `List<String>`.  

> Let us ignore what Java aka Open JDK javac currently does. 

I'm referencing the behavior of the jvm, not javac.

**Comment by agentgt** [comment] 2023-08-01 19:48
Yes but the parameterized type information is preserved depending on where (like methods or class definitions) but I agree your analogy is better in terms of erasure.

But just to be clear TYPE_USE annotations are available at runtime like I mentioned before (probably more so then generics).

> I'm referencing the behavior of the jvm, not javac.

Yeah I was kind of unclear on that because you have a video image of intellij and it looks like its patching in modules (my vision is bad so I can't say for sure). That goes to my point of what the tools do (especially JUnit but let us ignore that for now).

Anyway I assume as you do that `requires static` should be good enough but I'm saying I too have been seeing odd behavior in modular environments as well as GraalVM native. What avoids these headaches if the classes are actually present.

I made a case awhile back that JSpecify might want to consider having retention=CLASS as the Eclipse annotations do it that way but I found similar problems.

**Comment by agentgt** [comment] 2023-08-01 21:33
Just to be clear in a non-modular runtime (e.g. everything on classpath but jdk)  I have zero problems.

What I have seen in both Graal VM native and some jpackaged/jlinked environments are errors but it was not in that simple case you brought up. I should have isolated the problem but I lacked time.

Unfortunately the final executable jars in my companies environment are not using the module path so I have not been seeing the issue these days but I can certainly go testing with you as I need to know as well since I ship a library that does do `requires static org.eclipse-willeventuallbe.jspecify`.


What I think causes the issue is probably a bug in the annotation loading. If something calls A.class.getAnnotation(... any annotation ...) it will try to load `@NullMarked` even though it was not requested as all annotations get loaded. It should silently fail but I found that not to be in the case in certain environments.

Anyway here was some doc I think I was looking at when I came across the issue:

https://www.graalvm.org/sdk/javadoc/org/graalvm/nativeimage/AnnotationAccess.html

> The getAnnotation implementation in the JDK for Class, Field, and Method initializes the classes of all annotations present on that element, not just the class of the queried annotation. This leads to problems when not all annotation classes are present on the classpath/modulepath: querying an annotation whose class is present can fail with an exception because not all annotation classes are present.

Anyway I'll try to go back and reproduce my issues sometime next week and or collaborate with you on reproducing problems.

**Comment by cpovirk** [comment] 2024-03-18 22:02
We may also want to see what effect `optional` has on whatever Proguard plugins may exist for different build tools ([proguard-maven-plugin](https://github.com/wvengen/proguard-maven-plugin), [Proguard Gradle Plugin](https://www.guardsquare.com/manual/setup/gradleplugin)) and on the Android Gradle Plugin in general.

I base this on https://github.com/jhy/jsoup/issues/2129, which suggests that `optional` (or at least [`provided`](https://github.com/jhy/jsoup/blob/1f1f72d1e89821c630dcfc35e1a0a7f653cc877b/pom.xml#L448)) may be trouble.

\[edit: JSoup and R8 (not Proguard as I'd suggested initially) again in https://github.com/voultsanji1/toonitalia-/commit/50e0834fa599b8b0eebe1ff074a8712095c8776a#diff-09b2c99413460ebb90ea73560bea82a46996111028b6fbab31316433e58d42a8R15, so this still applies in July 2026. And later https://github.com/senkuboy0-cyber/Anime-Dekho/commit/45b5cf59750f5fa1e77170a209a51df2863d15e1, too. I should perhaps file an issue against JSoup, but I think it would mean more coming from an actual user.\]

**Comment by cpovirk** [comment] 2024-07-02 19:08
I'm going to close this in favor of #294 so that we have a single issue open for tracking purposes, but I'll refer back here.

**Closed by cpovirk** 2024-07-02 19:08 UTC
Labels: dev

**Comment by cpovirk** [comment] 2024-07-02 21:28
On the module front: Gradle suggests [a mapping between module directives and Gradle configurations](https://docs.gradle.org/current/userguide/java_library_plugin.html#declaring_module_dependencies). It says that `compileOnlyApi` (which is what I'd recommend if you really, really don't want the JSpecify annotations to be available at runtime) maps to `requires static transitive`. (And `api` maps to `requires transitive`.)
