### ISSUE TITLE
What guarantees for partially unspecified code?

### ISSUE THREAD

**Issue by stephan-herrmann** [jspecify/jspecify#93] opened 2020-01-21 22:11 UTC
If every type were either `@Nullable` or `@NonNull`, fully sound checking would be solvable by direct extension of the rules of the Java type system ("not less sound than Java itself" :) ). In the presence of `@NullnessUnspecified` or legacy code we have discussed many examples, but I'm not sure we're striving for the same level of guarantees.

After re-checking how Eclipse performs in this respect, I should say we are using a number of "common-sense" heuristics, but we (obviously) cannot guarantee that a warning free program is free of NPE.

The story towards users is: as long as unspecified types are involved, analysis is "best-effort". To get stronger guarantees, `@NonNullByDefault` must be used _everywhere_. (That's why we optionally raise a warning when any package is not annotated `@NonNullByDefault`).

The literature about **gradual typing** (which is in a way what we are trying here) has approaches with much more specific goals than the above. E.g., in "Well-typed programs can’t be blamed" the authors present a system, where **blame assignment** in case of an error will always point fingers towards the untyped part of the program. I seem to recall, however, that their approach does not cover mutable state (correct me if I'm wrong). Maybe other research about gradual typing will come in handy?

In my understanding, **shared access to mutable state** is the core of the problems we are facing here. Any object that is referenced both from specified and unspecified portions of the program will likely allow the unspecified portion to modify the object in ways that will break the specified portion. If we raise warnings for every data flow creating such shared access, then we will raise a lot of warnings, probably more than users would want.

A weaker description of a goal could be: analysis in the presence of unspecified parts is not more unsafe than similar structures with a mix of generics and **raw types**. This goal should provide a clear picture of what rules to check, but is it a good story to tell users? I'm undecided in this issue.

Do others have a clear and feasible idea of what we can promise regarding a program that is not fully annotated but warning free by our checkers?

**Comment by kevinb9n** [comment] 2021-07-19 20:37
Chris, is this issue the right place to track any current design decisions we need to make?

**Comment by cpovirk** [comment] 2021-07-19 21:08
One way to view this is as a duplicate of #115 (except, you know, that #115 came later :)).

This issue did raise more detailed questions, but then the conclusion of #115 was something like "Let's not get into the detailed questions." Or at least it was "Let's not get into the detailed questions more than we already do by defining rules for 'unspecified nullness' in the first place?" I think we have a pretty good story for how tools/users can pick a point on the spectrum from "Well-typed programs can’t be blamed" to "Hope for the best." And if JSpecify succeeds to the point that someone wants to explore this formally, that would make for an interesting read.

**Closed by cpovirk** 2021-07-19 21:08 UTC
Labels: nullness
